<?php
if (!isset($_SESSION['ADMIN_USERID'])) {
    redirect(web_root . "admin/index.php");
}

global $mydb;

$payroll_id = isset($_GET['id']) ? intval($_GET['id']) : 0;

// Get payroll details
$mydb->setQuery("SELECT * FROM tbl_payroll WHERE id = $payroll_id");
$mydb->executeQuery();
$payroll = $mydb->loadSingleResult();

if(!$payroll) {
    message("Payroll not found!", "error");
    redirect("index.php?view=payroll");
}

// Get school year
$mydb->setQuery("SELECT school_year FROM tbl_school_years WHERE id = '{$payroll->school_year_id}'");
$mydb->executeQuery();
$school_year = $mydb->loadSingleResult();

// Get creator name
$mydb->setQuery("SELECT FULLNAME FROM tblusers WHERE USERID = '{$payroll->created_by}'");
$mydb->executeQuery();
$creator = $mydb->loadSingleResult();

// Get approver name if approved
$approver = null;
if($payroll->approved_by) {
    $mydb->setQuery("SELECT FULLNAME FROM tblusers WHERE USERID = '{$payroll->approved_by}'");
    $mydb->executeQuery();
    $approver = $mydb->loadSingleResult();
}

// Get disburser name if disbursed
$disburser = null;
if($payroll->disbursed_by) {
    $mydb->setQuery("SELECT FULLNAME FROM tblusers WHERE USERID = '{$payroll->disbursed_by}'");
    $mydb->executeQuery();
    $disburser = $mydb->loadSingleResult();
}

// Get scholars for this payroll
$mydb->setQuery("
    SELECT pd.*, 
           CONCAT(a.LASTNAME, ', ', a.FIRSTNAME, ' ', IFNULL(a.MIDDLENAME, '')) as FULLNAME,
           a.MUNICIPALITY, 
           a.COURSE, 
           a.YEARLEVEL
    FROM tbl_payroll_details pd 
    INNER JOIN tbl_applicants a ON pd.scholar_id = a.APPLICANTID 
    WHERE pd.payroll_id = $payroll_id
    ORDER BY a.LASTNAME ASC
");
$mydb->executeQuery();
$scholars = $mydb->loadResultList();

// Count paid scholars
$paid_count = 0;
foreach($scholars as $scholar) {
    if($scholar->payment_status == 'paid') $paid_count++;
}
?>

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Payroll Details</h1>
    </div>
</div>

<!-- Action Buttons -->
<div class="row">
    <div class="col-lg-12" style="margin-bottom: 10px;">
        <a href="index.php?view=payroll" class="btn btn-default">
            <i class="fa fa-arrow-left"></i> Back to Payroll
        </a>
        <a href="index.php?view=print_payroll&id=<?php echo $payroll_id; ?>" class="btn btn-primary" target="_blank">
            <i class="fa fa-print"></i> Print Payroll
        </a>
        <?php if($payroll->status == 'pending' && ($_SESSION['ADMIN_ROLE'] == 'Super Admin' || $_SESSION['ADMIN_ROLE'] == 'Admin')): ?>
        <a href="controller.php?action=approve_payroll&id=<?php echo $payroll_id; ?>" class="btn btn-success" onclick="return confirm('Approve this payroll?')">
            <i class="fa fa-check"></i> Approve Payroll
        </a>
        <?php endif; ?>
        <?php if($payroll->status == 'pending' && ($_SESSION['ADMIN_ROLE'] == 'Super Admin' || $_SESSION['ADMIN_ROLE'] == 'Admin')): ?>
        <a href="controller.php?action=sync_payroll_scholars&id=<?php echo $payroll_id; ?>" class="btn btn-warning" onclick="return confirm('This will check for approved renewals that were not included when this payroll was generated and add them. Continue?')">
            <i class="fa fa-refresh"></i> Sync Renewed Scholars
        </a>
        <?php endif; ?>
        <?php if($payroll->status == 'approved' && ($_SESSION['ADMIN_ROLE'] == 'Super Admin' || $_SESSION['ADMIN_ROLE'] == 'Admin')): ?>
        <button onclick="disbursePayroll(<?php echo $payroll_id; ?>)" class="btn btn-primary">
            <i class="fa fa-money"></i> Mark as Disbursed
        </button>
        <?php endif; ?>
    </div>
</div>

<!-- Payroll Information -->
<div class="panel panel-info">
    <div class="panel-heading">
        <i class="fa fa-info-circle"></i> Payroll Information
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                <table class="table table-bordered">
                    <tr>
                        <th width="40%">School Year:</th>
                        <td><strong><?php echo $school_year ? $school_year->school_year : 'N/A'; ?></strong></td>
                    </tr>
                    <tr>
                        <th>Semester:</th>
                        <td><strong><?php echo $payroll->semester; ?></strong></td>
                    </tr>
                    <tr>
                        <th>Payment/Schedule Date:</th>
                        <td><?php echo date('F d, Y', strtotime($payroll->payment_date)); ?></td>
                    </tr>
                    <tr>
                        <th>Generated Date:</th>
                        <td><?php echo date('F d, Y h:i A', strtotime($payroll->created_at)); ?></td>
                    </tr>
                    <tr>
                        <th>Generated By:</th>
                        <td><?php echo $creator ? $creator->FULLNAME : 'N/A'; ?></td>
                    </tr>
                </table>
            </div>
            <div class="col-md-6">
                <table class="table table-bordered">
                    <tr>
                        <th width="40%">Status:</th>
                        <td>
                            <?php
                            $status_class = '';
                            switch($payroll->status) {
                                case 'pending': $status_class = 'warning'; break;
                                case 'approved': $status_class = 'info'; break;
                                case 'disbursed': $status_class = 'success'; break;
                                case 'cancelled': $status_class = 'danger'; break;
                            }
                            ?>
                            <span class="label label-<?php echo $status_class; ?>" style="font-size: 12px;">
                                <?php echo strtoupper($payroll->status); ?>
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <th>Total Amount:</th>
                        <td><strong style="font-size: 18px; color: #27ae60;">₱ <?php echo number_format($payroll->total_amount, 2); ?></strong></td>
                    </tr>
                    <tr>
                        <th>Total Scholars:</th>
                        <td><?php echo count($scholars); ?></td>
                    </tr>
                    <tr>
                        <th>Paid Scholars:</th>
                        <td><?php echo $paid_count; ?> / <?php echo count($scholars); ?></td>
                    </tr>
                    <?php if($payroll->remarks): ?>
                    <tr>
                        <th>Remarks:</th>
                        <td><?php echo $payroll->remarks; ?></td>
                    </tr>
                    <?php endif; ?>
                </table>
            </div>
        </div>
        
        <?php if($payroll->status == 'approved' && $payroll->approved_date): ?>
        <div class="alert alert-info" style="margin-top: 10px;">
            <i class="fa fa-check"></i> Approved on: <?php echo date('F d, Y h:i A', strtotime($payroll->approved_date)); ?>
            <?php if($approver): ?>
            <br><small>Approved by: <?php echo $approver->FULLNAME; ?></small>
            <?php endif; ?>
        </div>
        <?php endif; ?>
        
        <?php if($payroll->status == 'disbursed'): ?>
        <div class="alert alert-success" style="margin-top: 10px;">
            <i class="fa fa-check-circle"></i> This payroll has been disbursed.
            <?php if($payroll->disbursement_date): ?>
            <br><small>Disbursed on: <?php echo date('F d, Y h:i A', strtotime($payroll->disbursement_date)); ?></small>
            <?php endif; ?>
            <?php if($payroll->reference_no): ?>
            <br><small>Reference No.: <strong><?php echo $payroll->reference_no; ?></strong></small>
            <?php endif; ?>
            <?php if($disburser): ?>
            <br><small>Disbursed by: <?php echo $disburser->FULLNAME; ?></small>
            <?php endif; ?>
        </div>
        <?php endif; ?>
    </div>
</div>

<!-- Scholars List -->
<div class="panel panel-success">
    <div class="panel-heading">
        <i class="fa fa-graduation-cap"></i> Scholar Stipends List
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table id="scholars-table" class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Scholar Name</th>
                        <th>Municipality</th>
                        <th>Course</th>
                        <th>Year Level</th>
                        <th>Stipend Amount</th>
                        <th>Payment Status</th>
                        <th width="15%">Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                    $counter = 1;
                    foreach($scholars as $scholar):
                        $payment_status_class = $scholar->payment_status == 'paid' ? 'success' : 'warning';
                        $payment_status_text = $scholar->payment_status == 'paid' ? 'Paid' : 'Pending';
                    ?>
                    <tr>
                        <td class="text-center"><?php echo $counter++; ?></td>
                        <td><strong><?php echo $scholar->FULLNAME; ?></strong></td>
                        <td><?php echo $scholar->MUNICIPALITY; ?></td>
                        <td><?php echo $scholar->COURSE; ?></td>
                        <td><?php echo $scholar->YEARLEVEL; ?></td>
                        <td class="text-right">₱ <?php echo number_format($scholar->amount, 2); ?></td>
                        <td class="text-center">
                            <span class="label label-<?php echo $payment_status_class; ?>">
                                <?php echo $payment_status_text; ?>
                            </span>
                            <?php if($scholar->payment_date): ?>
                            <br><small><?php echo date('M d, Y', strtotime($scholar->payment_date)); ?></small>
                            <?php endif; ?>
                        </td>
                        <td class="text-center">
                            <?php if($scholar->payment_status != 'paid' && $payroll->status == 'approved'): ?>
                            <a href="controller.php?action=mark_stipend_paid&detail_id=<?php echo $scholar->id; ?>&payroll_id=<?php echo $payroll_id; ?>" 
                               class="btn btn-success btn-xs" onclick="return confirm('Mark stipend for <?php echo $scholar->FULLNAME; ?> as paid?')">
                                <i class="fa fa-check"></i> Mark Paid
                            </a>
                            <?php endif; ?>
                            <?php if($scholar->payment_status == 'paid'): ?>
                            <button class="btn btn-default btn-xs" disabled>
                                <i class="fa fa-check-circle"></i> Paid
                            </button>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                    
                    <?php if(empty($scholars)): ?>
                    <tr>
                        <td colspan="8" class="text-center">No scholars found for this payroll.</td>
                    </tr>
                    <?php endif; ?>
                </tbody>
                <tfoot>
                    <tr class="bg-gray" style="font-weight: bold;">
                        <td colspan="5" class="text-right"><strong>TOTAL:</strong></td>
                        <td class="text-right"><strong>₱ <?php echo number_format($payroll->total_amount, 2); ?></strong></td>
                        <td colspan="2"></td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

<script>
$(document).ready(function() {
    $('#scholars-table').DataTable({
        "pageLength": 25,
        "order": [[1, "asc"]],
        "columnDefs": [
            { "orderable": false, "targets": [0, 6, 7] }
        ]
    });
});

function disbursePayroll(id) {
    var reference = prompt("Enter Reference Number:", "PAY-" + new Date().toISOString().slice(0,10).replace(/-/g,'') + "-" + id);
    if(reference) {
        var form = $('<form action="controller.php?action=disburse_payroll&id=' + id + '" method="POST">' +
            '<input type="hidden" name="reference_no" value="' + reference + '">' +
            '</form>');
        $('body').append(form);
        form.submit();
    }
}
</script>